/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d8695e7868d0ef05351d53ce49d46cae)
interface __BaseEnv_Env {
	PARTICIPATION_USER_RATE_LIMITER: RateLimit;
	PARTICIPATION_IP_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	PARTICIPATION_CLEARANCE_KEY: string;
	PARTICIPATION_PROXY_HMAC_KEY: string;
	PARTICIPATION_IP_HMAC_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/sites-static");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_ANON_KEY" | "TURNSTILE_SECRET_KEY" | "PARTICIPATION_CLEARANCE_KEY" | "PARTICIPATION_PROXY_HMAC_KEY" | "PARTICIPATION_IP_HMAC_KEY">> {}
}
