#!/usr/bin/env python3
"""Build reviewed KMT and DPP party-officer data from official sources."""

from __future__ import annotations

import hashlib
import json
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "data-sources/major-parties/current-officers.json"
REPORT_PATH = ROOT / "data-sources/major-parties/officer-match-report.json"
SEED_PATH = ROOT / "data-sources/major-parties/official-officers.seed.json"
MIGRATION_PATH = ROOT / "supabase/migrations/202607260004_major_party_officers.sql"

MANUAL_MATCHES = {
    "何博文": "8969a11b-cbe0-4182-b759-8edcbe58e68b",
    "吳宗憲": "de2668ba-8834-427c-ae45-d1f8d0f21e49",
    "李乾龍": "99b5d0c9-24c3-4ec7-8bb0-fdcc3ae78463",
}

REVIEWED_MERGES = [
    {
        "duplicate_person_id": "9ed2328f-65e9-4d14-bace-458b68d38359",
        "canonical_person_id": "8969a11b-cbe0-4182-b759-8edcbe58e68b",
        "reason": "The 2018 councilor and 2012/2024 legislative records use the same name, party, and VoteTW person page; the official DPP roster confirms the current identity.",
        "source_url": "https://www.dpp.org.tw/about/political",
    },
    {
        "duplicate_person_id": "a965ae47-633a-4b9b-98c2-4ceecdeaefc6",
        "canonical_person_id": "99b5d0c9-24c3-4ec7-8bb0-fdcc3ae78463",
        "reason": "The 2012 and 2016 legislative records share the same uncommon name, party, and New Taipei City district; the official KMT roster confirms the current identity.",
        "source_url": "https://www.kmt.org.tw/2026/02/blog-post_23.html",
    },
]

PARTY_SLUGS = {
    "中國國民黨": "kmt",
    "民主進步黨": "dpp",
}


def stable_uuid(party_name: str, name: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"https://vote-select.tw/party-officer/{party_name}/{name}"))


def stable_key(*parts: str) -> str:
    return hashlib.sha1(": ".join(parts).encode("utf-8")).hexdigest()[:16]


def build_seed() -> dict[str, object]:
    source = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    matches = {item["name"]: item for item in report["matches"]}
    new_names = {item["name"] for item in report["matches"] if item["match_status"] == "not_found"}
    person_ids: dict[str, str] = {}
    for name, match in matches.items():
        if name in MANUAL_MATCHES:
            person_ids[name] = MANUAL_MATCHES[name]
        elif name in new_names:
            party_name = next(item["party_name"] for item in source["officers"] if item["name"] == name)
            person_ids[name] = stable_uuid(party_name, name)
        elif match["match_status"] == "unique_name":
            person_ids[name] = match["candidates"][0]["person_id"]
        else:
            raise RuntimeError(f"Unreviewed officer identity: {name}")

    officers = []
    for officer in source["officers"]:
        row = dict(officer)
        row["person_id"] = person_ids[officer["name"]]
        row["create_person"] = officer["name"] in new_names
        slug = PARTY_SLUGS[officer["party_name"]]
        role_key = stable_key(officer["name"], officer["role_title"], officer["organization_unit"])
        row["source_person_key"] = f"official-site:{slug}:party-officer:{role_key}"
        row["affiliation_key"] = f"official-party-role:{slug}:{row['person_id']}:{role_key}"
        officers.append(row)

    return {
        "observed_date": source["observed_date"],
        "date_semantics": source["date_semantics"],
        "officers": officers,
        "reviewed_merges": REVIEWED_MERGES,
    }


def build_migration(seed: dict[str, object]) -> str:
    officers_json = json.dumps(seed["officers"], ensure_ascii=False, separators=(",", ":"))
    merges_json = json.dumps(seed["reviewed_merges"], ensure_ascii=False, separators=(",", ":"))
    observed_date = seed["observed_date"]
    return f"""-- Generated by scripts/build-major-party-officer-migration.py from reviewed official party sources.
CREATE TEMP TABLE _major_party_officers AS
SELECT *
FROM jsonb_to_recordset($officers${officers_json}$officers$::JSONB) AS officer(
    party_name TEXT,
    name TEXT,
    role_title TEXT,
    organization_unit TEXT,
    is_current BOOLEAN,
    start_date DATE,
    end_date DATE,
    appointment_announced_date DATE,
    source_name TEXT,
    source_url TEXT,
    display_order INT,
    person_id UUID,
    create_person BOOLEAN,
    source_person_key TEXT,
    affiliation_key TEXT
);

CREATE TEMP TABLE _reviewed_party_person_merges AS
SELECT *
FROM jsonb_to_recordset($merges${merges_json}$merges$::JSONB) AS merge_row(
    duplicate_person_id UUID,
    canonical_person_id UUID,
    reason TEXT,
    source_url TEXT
);

INSERT INTO person_merge_decisions (
    duplicate_person_id, canonical_person_id, status, confidence_level, reason,
    evidence_json, reviewed_by, reviewed_at, updated_at
)
SELECT
    merge_row.duplicate_person_id,
    merge_row.canonical_person_id,
    'verified',
    'A',
    merge_row.reason,
    jsonb_build_object(
        'version', 'official-major-party-officer-review-v1',
        'sourceUrl', merge_row.source_url,
        'observedDate', '{observed_date}'
    ),
    'system:official-major-party-review',
    NOW(),
    NOW()
FROM _reviewed_party_person_merges merge_row
JOIN people duplicate ON duplicate.id = merge_row.duplicate_person_id
JOIN people canonical ON canonical.id = merge_row.canonical_person_id
WHERE NOT EXISTS (
    SELECT 1
    FROM person_merge_decisions existing
    WHERE existing.duplicate_person_id = merge_row.duplicate_person_id
      AND existing.status IN ('suggested', 'verified')
);

INSERT INTO people (id, name, party, position, source_url, is_public, created_at, updated_at)
SELECT DISTINCT ON (person_id)
    person_id,
    name,
    party_name,
    role_title,
    source_url,
    TRUE,
    NOW(),
    NOW()
FROM _major_party_officers
WHERE create_person = TRUE
ORDER BY person_id, is_current DESC, display_order
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    source_url = EXCLUDED.source_url,
    is_public = TRUE,
    updated_at = NOW();

INSERT INTO source_people (
    source_person_key, source_type, source_id, source_name, source_url,
    raw_name, normalized_name, party, normalized_party, position,
    source_payload, confidence_suggestion, ingest_batch_key, is_public, updated_at
)
SELECT
    source_person_key,
    'official_site',
    REPLACE(source_person_key, 'official-site:', ''),
    source_name,
    source_url,
    name,
    name,
    party_name,
    party_name,
    role_title,
    jsonb_strip_nulls(jsonb_build_object(
        'roleTitle', role_title,
        'organizationUnit', organization_unit,
        'isCurrent', is_current,
        'startDate', start_date,
        'endDate', end_date,
        'appointmentAnnouncedDate', appointment_announced_date,
        'observedDate', '{observed_date}',
        'dateSemantics', 'official_effective_dates_or_roster_observation'
    )),
    'A',
    'major-party-official-officers-20260726',
    TRUE,
    NOW()
FROM _major_party_officers
ON CONFLICT (source_person_key) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    raw_name = EXCLUDED.raw_name,
    normalized_name = EXCLUDED.normalized_name,
    party = EXCLUDED.party,
    normalized_party = EXCLUDED.normalized_party,
    position = EXCLUDED.position,
    source_payload = EXCLUDED.source_payload,
    confidence_suggestion = EXCLUDED.confidence_suggestion,
    ingest_batch_key = EXCLUDED.ingest_batch_key,
    is_public = EXCLUDED.is_public,
    updated_at = NOW();

INSERT INTO person_identity_matches (
    source_person_id, person_id, match_status, score, match_method, match_reason,
    evidence_json, reviewed_by, reviewed_at, updated_at
)
SELECT
    source.id,
    officer.person_id,
    'auto_matched',
    100,
    'manual_official_party_roster_review',
    'Official party officer source matched to the reviewed canonical person identity.',
    jsonb_build_object(
        'sourcePersonKey', officer.source_person_key,
        'observedDate', '{observed_date}',
        'roleTitle', officer.role_title
    ),
    'system:official-major-party-review',
    NOW(),
    NOW()
FROM _major_party_officers officer
JOIN source_people source ON source.source_person_key = officer.source_person_key
ON CONFLICT (source_person_id, person_id) DO UPDATE SET
    match_status = EXCLUDED.match_status,
    score = EXCLUDED.score,
    match_method = EXCLUDED.match_method,
    match_reason = EXCLUDED.match_reason,
    evidence_json = EXCLUDED.evidence_json,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = NOW();

INSERT INTO person_party_affiliations (
    affiliation_key, person_id, source_person_id, party_name, normalized_party,
    role_context, role_title, organization_unit, display_order,
    observed_year, observed_date, start_date, end_date, is_current,
    confidence_level, review_status, source_name, source_url,
    source_payload, is_public, created_at, updated_at
)
SELECT
    officer.affiliation_key,
    officer.person_id,
    source.id,
    officer.party_name,
    officer.party_name,
    'party_officer',
    officer.role_title,
    officer.organization_unit,
    officer.display_order,
    2026,
    DATE '{observed_date}',
    officer.start_date,
    officer.end_date,
    officer.is_current,
    'A',
    'verified',
    officer.source_name,
    officer.source_url,
    source.source_payload,
    TRUE,
    NOW(),
    NOW()
FROM _major_party_officers officer
JOIN source_people source ON source.source_person_key = officer.source_person_key
ON CONFLICT (affiliation_key) DO UPDATE SET
    person_id = EXCLUDED.person_id,
    source_person_id = EXCLUDED.source_person_id,
    party_name = EXCLUDED.party_name,
    normalized_party = EXCLUDED.normalized_party,
    role_context = EXCLUDED.role_context,
    role_title = EXCLUDED.role_title,
    organization_unit = EXCLUDED.organization_unit,
    display_order = EXCLUDED.display_order,
    observed_year = EXCLUDED.observed_year,
    observed_date = EXCLUDED.observed_date,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    is_current = EXCLUDED.is_current,
    confidence_level = EXCLUDED.confidence_level,
    review_status = EXCLUDED.review_status,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    source_payload = EXCLUDED.source_payload,
    is_public = EXCLUDED.is_public,
    updated_at = NOW();

UPDATE people person
SET party = officer.party_name, updated_at = NOW()
FROM _major_party_officers officer
WHERE officer.person_id = person.id
  AND officer.is_current = TRUE
  AND person.party IS DISTINCT FROM officer.party_name;

UPDATE parties
SET
    chairperson_name = '鄭麗文',
    source_name = '第22屆第1次全代會 鄭麗文主席宣誓就職',
    source_url = 'https://www.kmt.org.tw/2025/11/221.html',
    updated_at = NOW()
WHERE name = '中國國民黨';

UPDATE parties
SET
    chairperson_name = '賴清德',
    source_name = '民進黨主席及黨務主管',
    source_url = 'https://www.dpp.org.tw/about/political',
    updated_at = NOW()
WHERE name = '民主進步黨';

REFRESH MATERIALIZED VIEW public_people_list_cached;
"""


def main() -> None:
    seed = build_seed()
    SEED_PATH.write_text(json.dumps(seed, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    MIGRATION_PATH.write_text(build_migration(seed), encoding="utf-8")
    created = sum(officer["create_person"] for officer in seed["officers"])
    print(f"Wrote {len(seed['officers'])} party roles ({created} new-person role rows)")


if __name__ == "__main__":
    main()
