#!/usr/bin/env python3
"""Build the reviewed KMT/DPP officer expansion and profile migration."""

from __future__ import annotations

import hashlib
import json
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OFFICER_PATH = ROOT / "data-sources/major-parties/additional-current-officers.json"
PROFILE_PATH = ROOT / "data-sources/major-parties/kmt-official-profiles.json"
REPORT_PATH = ROOT / "data-sources/major-parties/officer-match-report.json"
SEED_PATH = ROOT / "data-sources/major-parties/official-officer-expansion.seed.json"
MIGRATION_PATH = ROOT / "supabase/migrations/202607260005_major_party_officer_expansion.sql"

MANUAL_MATCHES = {
    "萬美玲": "4f25892a-b0c5-484e-bb26-88f1e7aea483",
}

# These names collide with unrelated local-election people in the current database.
FORCE_NEW_NAMES = {"王建智", "吳易翰", "劉秀專", "陳俊良"}

PARTY_SLUGS = {
    "中國國民黨": "kmt",
    "民主進步黨": "dpp",
}


def stable_uuid(party_name: str, name: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"https://vote-select.tw/party-officer/{party_name}/{name}"))


def stable_key(*parts: str) -> str:
    return hashlib.sha1(": ".join(parts).encode("utf-8")).hexdigest()[:16]


def role_tier(officer: dict[str, object]) -> str:
    if officer["party_name"] == "中國國民黨" and officer["name"] == "萬美玲":
        return "primary"
    return "secondary"


def build_seed() -> dict[str, object]:
    source = json.loads(OFFICER_PATH.read_text(encoding="utf-8"))
    profiles_source = json.loads(PROFILE_PATH.read_text(encoding="utf-8"))
    report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    matches = {item["name"]: item for item in report["matches"]}

    party_by_name = {
        officer["name"]: officer["party_name"]
        for officer in source["officers"]
    }
    party_by_name.update({profile["name"]: "中國國民黨" for profile in profiles_source["profiles"]})

    person_ids: dict[str, str] = {}
    new_names: set[str] = set()
    for name, party_name in party_by_name.items():
        match = matches[name]
        if name in MANUAL_MATCHES:
            person_ids[name] = MANUAL_MATCHES[name]
        elif name in FORCE_NEW_NAMES or match["match_status"] == "not_found":
            person_ids[name] = stable_uuid(party_name, name)
            new_names.add(name)
        elif match["match_status"] == "unique_name":
            person_ids[name] = match["candidates"][0]["person_id"]
        else:
            raise RuntimeError(f"Unreviewed officer identity: {name}")

    officers = []
    for officer in source["officers"]:
        row = dict(officer)
        row["person_id"] = person_ids[row["name"]]
        row["create_person"] = row["name"] in new_names
        row["role_tier"] = role_tier(row)
        slug = PARTY_SLUGS[row["party_name"]]
        role_key = stable_key(row["name"], row["role_title"], row["organization_unit"])
        row["source_person_key"] = f"official-site:{slug}:party-officer:{role_key}"
        row["affiliation_key"] = f"official-party-role:{slug}:{row['person_id']}:{role_key}"
        officers.append(row)

    profiles = []
    for profile in profiles_source["profiles"]:
        row = dict(profile)
        row["person_id"] = person_ids[row["name"]]
        row["create_person"] = row["name"] in new_names
        row["source_person_key"] = f"official-site:kmt:profile:{stable_key(row['name'])}"
        profiles.append(row)

    return {
        "observed_date": source["observed_date"],
        "officers": officers,
        "profiles": profiles,
        "identity_review": {
            "manual_matches": MANUAL_MATCHES,
            "forced_new_people": sorted(FORCE_NEW_NAMES),
        },
    }


def build_migration(seed: dict[str, object]) -> str:
    officers_json = json.dumps(seed["officers"], ensure_ascii=False, separators=(",", ":"))
    profiles_json = json.dumps(seed["profiles"], ensure_ascii=False, separators=(",", ":"))
    observed_date = seed["observed_date"]
    return f"""-- Generated by scripts/build-major-party-officer-expansion.py from reviewed official party sources.
ALTER TABLE person_party_affiliations
    ADD COLUMN IF NOT EXISTS role_tier TEXT NOT NULL DEFAULT 'primary';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'person_party_affiliations_role_tier_check'
    ) THEN
        ALTER TABLE person_party_affiliations
            ADD CONSTRAINT person_party_affiliations_role_tier_check
            CHECK (role_tier IN ('primary', 'secondary', 'committee'));
    END IF;
END $$;

UPDATE person_party_affiliations
SET role_tier = 'secondary', updated_at = NOW()
WHERE role_context = 'party_officer'
  AND REPLACE(normalized_party, '臺', '台') = '台灣民眾黨'
  AND (
      COALESCE(display_order, 0) >= 100
      OR role_title LIKE '%中央委員%'
      OR role_title LIKE '%中央評議委員%'
  );

CREATE TEMP TABLE _major_party_officer_expansion AS
SELECT *
FROM jsonb_to_recordset($officers${officers_json}$officers$::JSONB) AS officer(
    party_name TEXT,
    name TEXT,
    role_title TEXT,
    organization_unit TEXT,
    is_current BOOLEAN,
    start_date DATE,
    end_date DATE,
    appointment_announced_date DATE,
    source_name TEXT,
    source_url TEXT,
    display_order INT,
    person_id UUID,
    create_person BOOLEAN,
    role_tier TEXT,
    source_person_key TEXT,
    affiliation_key TEXT
);

CREATE TEMP TABLE _kmt_official_profiles AS
SELECT *
FROM jsonb_to_recordset($profiles${profiles_json}$profiles$::JSONB) AS profile(
    name TEXT,
    english_name TEXT,
    title TEXT,
    education JSONB,
    experience JSONB,
    image_url TEXT,
    source_url TEXT,
    person_id UUID,
    create_person BOOLEAN,
    source_person_key TEXT
);

INSERT INTO people (id, name, party, position, source_url, is_public, created_at, updated_at)
SELECT DISTINCT ON (person_id)
    person_id, name, party_name, role_title, source_url, TRUE, NOW(), NOW()
FROM _major_party_officer_expansion
WHERE create_person = TRUE
ORDER BY person_id, display_order
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    source_url = COALESCE(people.source_url, EXCLUDED.source_url),
    is_public = TRUE,
    updated_at = NOW();

INSERT INTO source_people (
    source_person_key, source_type, source_id, source_name, source_url,
    raw_name, normalized_name, party, normalized_party, position,
    source_payload, confidence_suggestion, ingest_batch_key, is_public, updated_at
)
SELECT
    source_person_key,
    'official_site',
    REPLACE(source_person_key, 'official-site:', ''),
    source_name,
    source_url,
    name,
    name,
    party_name,
    party_name,
    role_title,
    jsonb_strip_nulls(jsonb_build_object(
        'roleTitle', role_title,
        'organizationUnit', organization_unit,
        'roleTier', role_tier,
        'isCurrent', is_current,
        'startDate', start_date,
        'endDate', end_date,
        'appointmentAnnouncedDate', appointment_announced_date,
        'observedDate', '{observed_date}'
    )),
    'A',
    'major-party-officer-expansion-20260726',
    TRUE,
    NOW()
FROM _major_party_officer_expansion
ON CONFLICT (source_person_key) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    party = EXCLUDED.party,
    normalized_party = EXCLUDED.normalized_party,
    position = EXCLUDED.position,
    source_payload = EXCLUDED.source_payload,
    confidence_suggestion = EXCLUDED.confidence_suggestion,
    ingest_batch_key = EXCLUDED.ingest_batch_key,
    is_public = EXCLUDED.is_public,
    updated_at = NOW();

INSERT INTO source_people (
    source_person_key, source_type, source_id, source_name, source_url,
    raw_name, normalized_name, party, normalized_party, position,
    source_payload, confidence_suggestion, ingest_batch_key, is_public, updated_at
)
SELECT
    source_person_key,
    'official_site',
    REPLACE(source_person_key, 'official-site:kmt:profile:', ''),
    '中國國民黨全球資訊網：現任黨務主管個人資料',
    source_url,
    name,
    name,
    '中國國民黨',
    '中國國民黨',
    title,
    jsonb_strip_nulls(jsonb_build_object(
        'englishName', english_name,
        'title', title,
        'education', education,
        'experience', experience,
        'imageUrl', image_url,
        'observedDate', '{observed_date}'
    )),
    'A',
    'kmt-official-profiles-20260726',
    TRUE,
    NOW()
FROM _kmt_official_profiles
ON CONFLICT (source_person_key) DO UPDATE SET
    source_url = EXCLUDED.source_url,
    position = EXCLUDED.position,
    source_payload = EXCLUDED.source_payload,
    confidence_suggestion = EXCLUDED.confidence_suggestion,
    ingest_batch_key = EXCLUDED.ingest_batch_key,
    is_public = EXCLUDED.is_public,
    updated_at = NOW();

INSERT INTO person_identity_matches (
    source_person_id, person_id, match_status, score, match_method, match_reason,
    evidence_json, reviewed_by, reviewed_at, updated_at
)
SELECT
    source.id,
    officer.person_id,
    'auto_matched',
    100,
    CASE WHEN officer.create_person THEN 'official_roster_new_person' ELSE 'reviewed_official_roster_match' END,
    CASE
        WHEN officer.create_person THEN 'Official party roster created a distinct person after same-name collision review.'
        ELSE 'Official party roster matched to the reviewed canonical identity.'
    END,
    jsonb_build_object('sourcePersonKey', officer.source_person_key, 'observedDate', '{observed_date}'),
    'system:major-party-officer-expansion',
    NOW(),
    NOW()
FROM _major_party_officer_expansion officer
JOIN source_people source ON source.source_person_key = officer.source_person_key
ON CONFLICT (source_person_id, person_id) DO UPDATE SET
    match_status = EXCLUDED.match_status,
    score = EXCLUDED.score,
    match_method = EXCLUDED.match_method,
    match_reason = EXCLUDED.match_reason,
    evidence_json = EXCLUDED.evidence_json,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = NOW();

INSERT INTO person_identity_matches (
    source_person_id, person_id, match_status, score, match_method, match_reason,
    evidence_json, reviewed_by, reviewed_at, updated_at
)
SELECT
    source.id,
    profile.person_id,
    'auto_matched',
    100,
    'reviewed_official_profile_match',
    'Official KMT profile matched to the reviewed current officer identity.',
    jsonb_build_object('sourcePersonKey', profile.source_person_key, 'observedDate', '{observed_date}'),
    'system:kmt-official-profiles',
    NOW(),
    NOW()
FROM _kmt_official_profiles profile
JOIN source_people source ON source.source_person_key = profile.source_person_key
ON CONFLICT (source_person_id, person_id) DO UPDATE SET
    match_status = EXCLUDED.match_status,
    score = EXCLUDED.score,
    match_method = EXCLUDED.match_method,
    match_reason = EXCLUDED.match_reason,
    evidence_json = EXCLUDED.evidence_json,
    reviewed_by = EXCLUDED.reviewed_by,
    reviewed_at = EXCLUDED.reviewed_at,
    updated_at = NOW();

INSERT INTO person_party_affiliations (
    affiliation_key, person_id, source_person_id, party_name, normalized_party,
    role_context, role_title, organization_unit, display_order, role_tier,
    observed_year, observed_date, start_date, end_date, is_current,
    confidence_level, review_status, source_name, source_url,
    source_payload, is_public, created_at, updated_at
)
SELECT
    officer.affiliation_key,
    officer.person_id,
    source.id,
    officer.party_name,
    officer.party_name,
    'party_officer',
    officer.role_title,
    officer.organization_unit,
    officer.display_order,
    officer.role_tier,
    2026,
    DATE '{observed_date}',
    officer.start_date,
    officer.end_date,
    officer.is_current,
    'A',
    'verified',
    officer.source_name,
    officer.source_url,
    source.source_payload,
    TRUE,
    NOW(),
    NOW()
FROM _major_party_officer_expansion officer
JOIN source_people source ON source.source_person_key = officer.source_person_key
ON CONFLICT (affiliation_key) DO UPDATE SET
    person_id = EXCLUDED.person_id,
    source_person_id = EXCLUDED.source_person_id,
    role_title = EXCLUDED.role_title,
    organization_unit = EXCLUDED.organization_unit,
    display_order = EXCLUDED.display_order,
    role_tier = EXCLUDED.role_tier,
    observed_date = EXCLUDED.observed_date,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    is_current = EXCLUDED.is_current,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    source_payload = EXCLUDED.source_payload,
    is_public = EXCLUDED.is_public,
    updated_at = NOW();

WITH claim_rows AS (
    SELECT
        profile.*,
        claim.claim_type,
        claim.items,
        ARRAY_TO_STRING(ARRAY(SELECT jsonb_array_elements_text(claim.items)), '；') AS claim_value
    FROM _kmt_official_profiles profile
    CROSS JOIN LATERAL (
        VALUES ('education', profile.education), ('experience', profile.experience)
    ) AS claim(claim_type, items)
    WHERE jsonb_array_length(claim.items) > 0
)
INSERT INTO person_claims (
    claim_key, person_id, source_person_id, claim_type, claim_value, claim_json,
    confidence_level, review_status, visibility, source_name, source_url,
    observed_at, is_public, review_score, scoring_version, scoring_reasons,
    auto_reviewed_at, updated_at
)
SELECT
    claim.source_person_key || ':' || claim.claim_type,
    claim.person_id,
    source.id,
    claim.claim_type,
    claim.claim_value,
    source.source_payload || jsonb_build_object('field', claim.claim_type),
    'A',
    'verified',
    'public',
    '中國國民黨全球資訊網：現任黨務主管個人資料',
    claim.source_url,
    TIMESTAMPTZ '{observed_date} 00:00:00+08',
    TRUE,
    100,
    'official-party-profile-v1',
    jsonb_build_array('Official party profile.'),
    NOW(),
    NOW()
FROM claim_rows claim
JOIN source_people source ON source.source_person_key = claim.source_person_key
ON CONFLICT (claim_key) DO UPDATE SET
    person_id = EXCLUDED.person_id,
    source_person_id = EXCLUDED.source_person_id,
    claim_value = EXCLUDED.claim_value,
    claim_json = EXCLUDED.claim_json,
    confidence_level = EXCLUDED.confidence_level,
    review_status = EXCLUDED.review_status,
    visibility = EXCLUDED.visibility,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    observed_at = EXCLUDED.observed_at,
    is_public = EXCLUDED.is_public,
    review_score = EXCLUDED.review_score,
    scoring_version = EXCLUDED.scoring_version,
    scoring_reasons = EXCLUDED.scoring_reasons,
    auto_reviewed_at = EXCLUDED.auto_reviewed_at,
    updated_at = NOW();

WITH profile_text AS (
    SELECT
        person_id,
        english_name,
        source_url,
        ARRAY_TO_STRING(ARRAY(SELECT jsonb_array_elements_text(education)), '；') AS education_value,
        ARRAY_TO_STRING(ARRAY(SELECT jsonb_array_elements_text(experience)), '；') AS experience_value
    FROM _kmt_official_profiles
)
UPDATE people person
SET
    alias = COALESCE(NULLIF(person.alias, ''), profile.english_name),
    education = CASE
        WHEN LENGTH(COALESCE(profile.education_value, '')) > LENGTH(COALESCE(person.education, ''))
            THEN profile.education_value
        ELSE person.education
    END,
    experience = CASE
        WHEN LENGTH(COALESCE(profile.experience_value, '')) > LENGTH(COALESCE(person.experience, ''))
            THEN profile.experience_value
        ELSE person.experience
    END,
    source_url = COALESCE(person.source_url, profile.source_url),
    updated_at = NOW()
FROM profile_text profile
WHERE profile.person_id = person.id;

UPDATE people person
SET party = officer.party_name, updated_at = NOW()
FROM _major_party_officer_expansion officer
WHERE officer.person_id = person.id
  AND officer.is_current = TRUE
  AND person.party IS DISTINCT FROM officer.party_name;

CREATE OR REPLACE VIEW public_person_party_affiliations AS
SELECT
    a.id AS affiliation_id,
    a.affiliation_key,
    a.person_id,
    p.name AS person_name,
    a.source_claim_key,
    a.party_name,
    a.role_context,
    a.role_title,
    a.organization_unit,
    a.display_order,
    a.observed_year,
    a.observed_date,
    a.start_date,
    a.end_date,
    a.is_current,
    a.confidence_level,
    a.source_name,
    a.source_url,
    a.updated_at,
    a.role_tier
FROM person_party_affiliations a
JOIN people p ON p.id = a.person_id AND p.is_public = TRUE
WHERE a.is_public = TRUE
  AND a.review_status = 'verified';

CREATE OR REPLACE VIEW public_party_officers AS
SELECT
    affiliation.id AS affiliation_id,
    affiliation.person_id,
    person.name AS person_name,
    party.id AS party_id,
    party.name AS party_name,
    affiliation.role_title,
    affiliation.organization_unit,
    affiliation.display_order,
    affiliation.start_date,
    affiliation.observed_date,
    profile.current_office_label,
    profile.primary_photo_thumbnail_url,
    affiliation.source_name,
    affiliation.source_url,
    affiliation.updated_at,
    affiliation.role_tier
FROM person_party_affiliations affiliation
JOIN people person ON person.id = affiliation.person_id AND person.is_public = TRUE
JOIN parties party
  ON party.is_public = TRUE
 AND REPLACE(party.name, '臺', '台') = REPLACE(affiliation.normalized_party, '臺', '台')
LEFT JOIN public_people_list_cached profile ON profile.person_id = affiliation.person_id
WHERE affiliation.role_context = 'party_officer'
  AND affiliation.is_current = TRUE
  AND affiliation.is_public = TRUE
  AND affiliation.review_status = 'verified';

DROP VIEW IF EXISTS public_people_directory;
CREATE VIEW public_people_directory AS
SELECT
    profile.*,
    (
        EXISTS (
            SELECT 1
            FROM person_party_affiliations affiliation
            WHERE affiliation.person_id = profile.person_id
              AND affiliation.role_context = 'party_officer'
              AND affiliation.is_current = TRUE
              AND affiliation.is_public = TRUE
              AND affiliation.review_status = 'verified'
        )
        AND profile.current_office_label IS NULL
        AND profile.upcoming_candidate_label IS NULL
        AND NOT EXISTS (
            SELECT 1 FROM public_candidates candidate
            WHERE candidate.person_id = profile.person_id
        )
    ) AS list_is_party_only
FROM public_people_list_cached profile;

REVOKE ALL ON public_people_directory FROM PUBLIC;
GRANT SELECT ON public_people_directory TO anon, authenticated;
GRANT SELECT ON public_person_party_affiliations TO anon, authenticated;
GRANT SELECT ON public_party_officers TO anon, authenticated;

REFRESH MATERIALIZED VIEW public_people_list_cached;
"""


def main() -> None:
    seed = build_seed()
    SEED_PATH.write_text(json.dumps(seed, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    MIGRATION_PATH.write_text(build_migration(seed), encoding="utf-8")
    created = sum(officer["create_person"] for officer in seed["officers"])
    print(f"Wrote {len(seed['officers'])} roles, {len(seed['profiles'])} profiles, {created} new-person role rows")


if __name__ == "__main__":
    main()
