-- Generated by scripts/build-2026-registration-polling-production-release.mjs
-- Applies the reviewed registration and polling-place cohort atomically.
BEGIN;
SET LOCAL lock_timeout = '15s';
SET LOCAL statement_timeout = '20min';
SELECT pg_advisory_xact_lock(hashtextextended('public-office-watch:2026-registration-polling-release', 0));

DO $check$
BEGIN
 IF (SELECT count(*) FROM release_staging_20260906._people_20260906) <> 17546 THEN RAISE EXCEPTION 'Staging count mismatch: people'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._races_20260906) <> 8254 THEN RAISE EXCEPTION 'Staging count mismatch: races'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._merge_decisions_20260906) <> 4 THEN RAISE EXCEPTION 'Staging count mismatch: merge_decisions'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._candidates_20260906) <> 17544 THEN RAISE EXCEPTION 'Staging count mismatch: candidates'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._lifecycle_events_20260906) <> 17500 THEN RAISE EXCEPTION 'Staging count mismatch: lifecycle_events'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._registration_roster_20260906) <> 916 THEN RAISE EXCEPTION 'Staging count mismatch: registration_roster'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._polling_sources_20260906) <> 15 THEN RAISE EXCEPTION 'Staging count mismatch: polling_sources'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._polling_places_20260906) <> 14790 THEN RAISE EXCEPTION 'Staging count mismatch: polling_places'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._polling_neighborhoods_20260906) <> 95670 THEN RAISE EXCEPTION 'Staging count mismatch: polling_neighborhoods'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._canonical_links_20260906) <> 6 THEN RAISE EXCEPTION 'Staging count mismatch: canonical_links'; END IF;
 IF (SELECT count(*) FROM release_staging_20260906._required_races_20260906) <> 8254 THEN RAISE EXCEPTION 'Staging count mismatch: required_races'; END IF;
 IF EXISTS (
   SELECT id FROM release_staging_20260906._candidates_20260906 GROUP BY id HAVING count(*) <> 1
 ) OR EXISTS (
   SELECT external_id FROM release_staging_20260906._candidates_20260906 GROUP BY external_id HAVING count(*) <> 1
 ) THEN RAISE EXCEPTION 'Duplicate staged candidate identity'; END IF;
 IF EXISTS (
   SELECT id FROM release_staging_20260906._polling_places_20260906 GROUP BY id HAVING count(*) <> 1
 ) THEN RAISE EXCEPTION 'Duplicate staged polling-place identity'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._people_20260906 staged
   JOIN public.people existing ON existing.id = staged.id
   WHERE existing.external_id IS DISTINCT FROM staged.external_id
      OR (
        existing.name IS DISTINCT FROM staged.name
        AND staged.id NOT IN ('147c1321-53d1-4dd3-89de-7823697c7098'::uuid,'2ec71727-7227-4ee6-a5dc-b16493f0ad27'::uuid,'c1a80678-c645-4bfb-8d93-73423c5f7aaa'::uuid)
      )
 ) THEN RAISE EXCEPTION 'Existing person identity differs from reviewed row'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._people_20260906 staged
   JOIN public.people existing ON existing.external_id = staged.external_id
   WHERE existing.id <> staged.id
 ) THEN RAISE EXCEPTION 'Reviewed person external_id belongs to another row'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._races_20260906 staged
   JOIN public.races existing ON existing.external_id = staged.external_id
   WHERE existing.id <> staged.id
 ) THEN RAISE EXCEPTION 'Reviewed race external_id belongs to another row'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._races_20260906 staged
   JOIN public.races existing ON existing.id = staged.id
   WHERE existing.external_id IS DISTINCT FROM staged.external_id
 ) THEN RAISE EXCEPTION 'Existing race identity differs from reviewed row'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._races_20260906 staged
   LEFT JOIN public.elections election ON election.id = staged.election_id
   LEFT JOIN public.regions region ON region.id = staged.region_id
   WHERE election.id IS NULL OR (staged.region_id IS NOT NULL AND region.id IS NULL)
 ) THEN RAISE EXCEPTION 'Reviewed race dependency is missing'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._required_races_20260906 dependency
   LEFT JOIN public.races existing ON existing.id = dependency.id
   LEFT JOIN release_staging_20260906._races_20260906 staged ON staged.id = dependency.id
   WHERE existing.id IS NULL AND staged.id IS NULL
 ) THEN RAISE EXCEPTION 'A required 2026 race is missing from production'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._candidates_20260906 staged
   LEFT JOIN public.people existing ON existing.id = staged.person_id
   LEFT JOIN release_staging_20260906._people_20260906 incoming ON incoming.id = staged.person_id
   WHERE existing.id IS NULL AND incoming.id IS NULL
 ) THEN RAISE EXCEPTION 'A candidate person dependency is missing from production'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._canonical_links_20260906 link
   LEFT JOIN public.people canonical ON canonical.id = link.canonical_person_id
   LEFT JOIN release_staging_20260906._people_20260906 incoming ON incoming.id = link.canonical_person_id
   WHERE canonical.id IS NULL AND incoming.id IS NULL
 ) THEN RAISE EXCEPTION 'A canonical person dependency is missing from production'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._merge_decisions_20260906 staged
   JOIN public.person_merge_decisions existing
     ON existing.duplicate_person_id = staged.duplicate_person_id
    AND existing.status IN ('suggested','verified')
   WHERE existing.id <> staged.id
 ) THEN RAISE EXCEPTION 'A reviewed duplicate person already has another active decision'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._candidates_20260906 staged
   JOIN public.candidates existing ON existing.id = staged.id
   WHERE existing.person_id <> staged.person_id
      OR existing.race_id <> staged.race_id
      OR existing.external_id IS DISTINCT FROM staged.external_id
 ) THEN RAISE EXCEPTION 'Existing candidate identity differs from reviewed row'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._candidates_20260906 staged
   JOIN public.candidates existing ON existing.external_id = staged.external_id
   WHERE existing.id <> staged.id
 ) THEN RAISE EXCEPTION 'Reviewed candidate external_id belongs to another row'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._candidates_20260906 staged
   JOIN public.candidates existing
     ON existing.person_id = staged.person_id AND existing.race_id = staged.race_id
   WHERE existing.id <> staged.id
 ) THEN RAISE EXCEPTION 'Reviewed person and race belong to another candidate row'; END IF;
 IF EXISTS (
   SELECT 1
   FROM public.polling_place_sources existing
   JOIN release_staging_20260906._polling_sources_20260906 staged
     ON staged.event_key = existing.event_key AND staged.county_code = existing.county_code
   WHERE existing.is_current AND existing.id <> staged.id
     AND existing.published_on > staged.published_on
 ) THEN RAISE EXCEPTION 'A newer polling-place source is already present'; END IF;
END
$check$;

CREATE TEMP TABLE current_office_before ON COMMIT DROP AS
SELECT person_id, list_role, current_office_label
FROM published.people
WHERE list_status = 'current';

INSERT INTO public.people
SELECT staged.*
FROM release_staging_20260906._people_20260906 staged
WHERE NOT EXISTS (SELECT 1 FROM public.people existing WHERE existing.id = staged.id);

UPDATE public.people target
SET position = staged.position,
    election_year = staged.election_year,
    district = staged.district,
    source_url = staged.source_url,
    is_public = staged.is_public,
    updated_at = staged.updated_at
FROM release_staging_20260906._people_20260906 staged
WHERE target.id = staged.id
  AND (
    staged.external_id LIKE 'pow-cec-registration-person-2026-%'
    OR staged.id IN ('567af1d0-5f8f-4e48-b6b1-cbf3a9d30110'::uuid,'b05ef122-1db5-442a-a3f5-0636f334c7f8'::uuid,'f4fc600d-a6c8-4788-b919-e9b3a8f252d6'::uuid)
  )
  AND ROW(target.position,target.election_year,target.district,target.source_url,target.is_public,target.updated_at)
      IS DISTINCT FROM
      ROW(staged.position,staged.election_year,staged.district,staged.source_url,staged.is_public,staged.updated_at);

UPDATE public.people target
SET name = staged.name,
    updated_at = staged.updated_at
FROM release_staging_20260906._people_20260906 staged
WHERE target.id = staged.id
  AND staged.id IN ('147c1321-53d1-4dd3-89de-7823697c7098'::uuid,'2ec71727-7227-4ee6-a5dc-b16493f0ad27'::uuid,'c1a80678-c645-4bfb-8d93-73423c5f7aaa'::uuid)
  AND ROW(target.name,target.updated_at)
      IS DISTINCT FROM ROW(staged.name,staged.updated_at);

INSERT INTO public.races
SELECT staged.*
FROM release_staging_20260906._races_20260906 staged
WHERE NOT EXISTS (SELECT 1 FROM public.races existing WHERE existing.id = staged.id);

UPDATE public.races target
SET election_id = staged.election_id,
    region_id = staged.region_id,
    race_type = staged.race_type,
    title = staged.title,
    voting_date = staged.voting_date,
    status = staged.status,
    source_name = staged.source_name,
    source_url = staged.source_url,
    is_public = staged.is_public,
    updated_at = staged.updated_at,
    external_id = staged.external_id,
    district_scope = staged.district_scope,
    seat_count = staged.seat_count,
    reserved_women_seat_count = staged.reserved_women_seat_count,
    campaign_expense_limit = staged.campaign_expense_limit
FROM release_staging_20260906._races_20260906 staged
WHERE target.id = staged.id
  AND to_jsonb(target) - 'created_at' IS DISTINCT FROM to_jsonb(staged) - 'created_at';

INSERT INTO public.person_merge_decisions
SELECT staged.*
FROM release_staging_20260906._merge_decisions_20260906 staged
WHERE NOT EXISTS (
  SELECT 1 FROM public.person_merge_decisions existing WHERE existing.id = staged.id
);

INSERT INTO public.candidates
SELECT staged.*
FROM release_staging_20260906._candidates_20260906 staged
WHERE NOT EXISTS (SELECT 1 FROM public.candidates existing WHERE existing.id = staged.id);

UPDATE public.candidates target
SET party = staged.party,
    candidate_no = staged.candidate_no,
    registration_status = staged.registration_status,
    source_name = staged.source_name,
    source_url = staged.source_url,
    is_public = staged.is_public,
    updated_at = staged.updated_at,
    vote_count = staged.vote_count,
    vote_rate = staged.vote_rate,
    is_elected = staged.is_elected,
    is_incumbent = staged.is_incumbent,
    candidacy_status = staged.candidacy_status,
    election_result = staged.election_result,
    status_updated_at = staged.status_updated_at
FROM release_staging_20260906._candidates_20260906 staged
WHERE target.id = staged.id
  AND ROW(target.party,target.candidate_no,target.registration_status,target.source_name,target.source_url,
          target.is_public,target.updated_at,target.vote_count,target.vote_rate,target.is_elected,
          target.is_incumbent,target.candidacy_status,target.election_result,target.status_updated_at)
      IS DISTINCT FROM
      ROW(staged.party,staged.candidate_no,staged.registration_status,staged.source_name,staged.source_url,
          staged.is_public,staged.updated_at,staged.vote_count,staged.vote_rate,staged.is_elected,
          staged.is_incumbent,staged.candidacy_status,staged.election_result,staged.status_updated_at);

INSERT INTO public.candidate_lifecycle_events
SELECT staged.*
FROM release_staging_20260906._lifecycle_events_20260906 staged
WHERE NOT EXISTS (
  SELECT 1 FROM public.candidate_lifecycle_events existing WHERE existing.id = staged.id
);

INSERT INTO public.registration_name_roster
SELECT staged.*
FROM release_staging_20260906._registration_roster_20260906 staged
WHERE NOT EXISTS (
  SELECT 1 FROM public.registration_name_roster existing WHERE existing.id = staged.id
);

UPDATE public.polling_place_sources source
SET is_current = FALSE
WHERE source.is_current
  AND EXISTS (
    SELECT 1
    FROM release_staging_20260906._polling_sources_20260906 staged
    WHERE staged.event_key = source.event_key
      AND staged.county_code = source.county_code
      AND staged.id <> source.id
  );

INSERT INTO public.polling_place_sources
SELECT staged.*
FROM release_staging_20260906._polling_sources_20260906 staged
WHERE NOT EXISTS (
  SELECT 1 FROM public.polling_place_sources existing WHERE existing.id = staged.id
);

INSERT INTO public.polling_places
SELECT staged.*
FROM release_staging_20260906._polling_places_20260906 staged
WHERE NOT EXISTS (
  SELECT 1 FROM public.polling_places existing WHERE existing.id = staged.id
);

INSERT INTO public.polling_place_neighborhoods
SELECT staged.*
FROM release_staging_20260906._polling_neighborhoods_20260906 staged
ON CONFLICT (polling_place_id, neighborhood_no) DO NOTHING;

SELECT public.refresh_public_people_list_cached();
SELECT published.promote(NULL);

DO $verify$
BEGIN
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._people_20260906 staged
   JOIN public.people actual ON actual.id = staged.id
   WHERE staged.id IN ('147c1321-53d1-4dd3-89de-7823697c7098'::uuid,'2ec71727-7227-4ee6-a5dc-b16493f0ad27'::uuid,'c1a80678-c645-4bfb-8d93-73423c5f7aaa'::uuid)
     AND actual.name IS DISTINCT FROM staged.name
 ) THEN RAISE EXCEPTION 'Reviewed person name corrections differ after release'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._merge_decisions_20260906 staged
   LEFT JOIN public.person_merge_decisions actual ON actual.id = staged.id
   WHERE to_jsonb(actual) IS DISTINCT FROM to_jsonb(staged)
 ) THEN RAISE EXCEPTION 'Reviewed identity decisions differ after release'; END IF;
 IF (
   SELECT count(*)
   FROM public.person_merge_decisions
   WHERE status = 'verified'
     AND evidence_json->>'reviewType' = '2026_registration_nominee_reconciliation'
 ) <> 4 THEN RAISE EXCEPTION 'Reviewed registration identity decision count differs'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._canonical_links_20260906 expected
   LEFT JOIN public.person_canonical_map actual ON actual.person_id = expected.person_id
   WHERE actual.canonical_person_id IS DISTINCT FROM expected.canonical_person_id
 ) THEN RAISE EXCEPTION 'Canonical person mapping differs after release'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._candidates_20260906 staged
   JOIN public.candidates actual ON actual.id = staged.id
   WHERE ROW(actual.person_id,actual.race_id,actual.party,actual.candidate_no,actual.registration_status,
             actual.source_name,actual.source_url,actual.is_public,actual.vote_count,actual.vote_rate,
             actual.is_elected,actual.is_incumbent,actual.external_id,actual.candidacy_status,
             actual.election_result)
         IS DISTINCT FROM
         ROW(staged.person_id,staged.race_id,staged.party,staged.candidate_no,staged.registration_status,
             staged.source_name,staged.source_url,staged.is_public,staged.vote_count,staged.vote_rate,
             staged.is_elected,staged.is_incumbent,staged.external_id,staged.candidacy_status,
             staged.election_result)
      OR actual.status_updated_at IS NULL
 ) THEN RAISE EXCEPTION 'Candidate facts differ after release'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._lifecycle_events_20260906 staged
   LEFT JOIN public.candidate_lifecycle_events actual ON actual.id = staged.id
   WHERE to_jsonb(actual) IS DISTINCT FROM to_jsonb(staged)
 ) THEN RAISE EXCEPTION 'Lifecycle facts differ after release'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._registration_roster_20260906 staged
   LEFT JOIN public.registration_name_roster actual ON actual.id = staged.id
   WHERE to_jsonb(actual) IS DISTINCT FROM to_jsonb(staged)
 ) THEN RAISE EXCEPTION 'Name-only roster differs after release'; END IF;
 IF EXISTS (
   SELECT 1
   FROM release_staging_20260906._polling_sources_20260906 staged
   LEFT JOIN public.polling_place_sources actual ON actual.id = staged.id
   WHERE to_jsonb(actual) IS DISTINCT FROM to_jsonb(staged)
 ) OR EXISTS (
   SELECT 1
   FROM release_staging_20260906._polling_places_20260906 staged
   LEFT JOIN public.polling_places actual ON actual.id = staged.id
   WHERE to_jsonb(actual) IS DISTINCT FROM to_jsonb(staged)
 ) OR EXISTS (
   SELECT 1
   FROM release_staging_20260906._polling_neighborhoods_20260906 staged
   LEFT JOIN public.polling_place_neighborhoods actual
     ON actual.polling_place_id = staged.polling_place_id
    AND actual.neighborhood_no = staged.neighborhood_no
   WHERE actual.polling_place_id IS NULL
 ) THEN RAISE EXCEPTION 'Polling-place facts differ after release'; END IF;
 IF (
   SELECT count(*)
   FROM public.candidates candidate
   JOIN public.races race ON race.id = candidate.race_id
   JOIN public.elections election ON election.id = race.election_id
   WHERE election.year = 2026
     AND candidate.candidacy_status = 'registered'
     AND candidate.registration_status = 'registered'
     AND candidate.election_result = 'pending'
     AND candidate.is_public
 ) <> 17500 THEN RAISE EXCEPTION 'Published registered candidate count differs'; END IF;
 IF (
   SELECT count(*) FROM public.registration_name_roster WHERE is_public
 ) <> 916 THEN RAISE EXCEPTION 'Published name-only registration count differs'; END IF;
 IF (
   SELECT count(*) FROM public.candidate_lifecycle_events
   WHERE external_id LIKE 'cec-registration-2026:%'
     AND event_type = 'registration_filed' AND is_public
 ) <> 17500 THEN RAISE EXCEPTION 'Published registration lifecycle count differs'; END IF;
 IF EXISTS (
   SELECT 1
   FROM public.candidates candidate
   JOIN public.races race ON race.id = candidate.race_id
   JOIN public.elections election ON election.id = race.election_id
   WHERE election.year = 2026
     AND (
       candidate.candidacy_status = 'party_nominee'
       OR candidate.election_result = 'elected'
       OR (candidate.candidacy_status = 'registered' AND candidate.candidate_no IS NOT NULL)
     )
 ) THEN RAISE EXCEPTION 'Registration release inferred nomination, election, or ballot number'; END IF;
 IF (
   SELECT count(*)
   FROM public.candidates candidate
   JOIN public.races race ON race.id = candidate.race_id
   JOIN public.elections election ON election.id = race.election_id
   WHERE election.year = 2026
     AND candidate.candidacy_status = 'did_not_register'
     AND candidate.registration_status = 'not_registered'
     AND NOT candidate.is_public
 ) <> 2 THEN RAISE EXCEPTION 'Did-not-register count differs'; END IF;
 IF (
   SELECT count(*)
   FROM public.candidates candidate
   JOIN public.races race ON race.id = candidate.race_id
   JOIN public.elections election ON election.id = race.election_id
   WHERE election.year = 2026
     AND candidate.candidacy_status = 'unknown'
     AND candidate.registration_status = 'unknown'
     AND NOT candidate.is_public
 ) <> 42 THEN RAISE EXCEPTION 'Withheld candidate count differs'; END IF;
 IF (SELECT count(*) FROM public.polling_place_sources WHERE is_public AND is_current) <> 15
    OR (SELECT count(*) FROM public.polling_places) <> 14790
    OR (SELECT count(*) FROM public.polling_place_neighborhoods) <> 95670
 THEN RAISE EXCEPTION 'Polling-place release count differs'; END IF;
 IF EXISTS (
   SELECT 1
   FROM current_office_before before
   FULL JOIN (
     SELECT person_id, list_role, current_office_label
     FROM published.people WHERE list_status = 'current'
   ) after USING (person_id)
   WHERE before.person_id IS NULL OR after.person_id IS NULL
      OR before.list_role IS DISTINCT FROM after.list_role
      OR before.current_office_label IS DISTINCT FROM after.current_office_label
 ) THEN RAISE EXCEPTION 'Current office roster changed during registration release'; END IF;
 IF EXISTS (
   SELECT 1
   FROM public.public_people person
   JOIN public.people base ON base.id = person.person_id
   WHERE base.external_id LIKE 'pow-cec-registration-person-2026-%'
     AND person.current_office_label IS NOT NULL
 ) THEN RAISE EXCEPTION 'Registration-only person gained a current office'; END IF;
 IF NOT EXISTS (
   SELECT 1
   FROM published.people
   WHERE person_id = '96c49dbf-21a1-467d-8acf-2e5f3b9a933f'::uuid
     AND position IS NULL
     AND current_office_label IS NULL
     AND upcoming_candidate_label = '臺北市市長'
     AND list_status = 'candidate'
 ) THEN RAISE EXCEPTION 'Guo Xi candidate/current-office separation failed'; END IF;
END
$verify$;

DROP SCHEMA release_staging_20260906 CASCADE;
NOTIFY pgrst, 'reload schema';
COMMIT;
