-- Generated by scripts/build-2026-registration-polling-production-release.mjs
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '5min';
INSERT INTO release_staging_20260906._canonical_links_20260906
SELECT *
FROM jsonb_populate_recordset(
  NULL::release_staging_20260906._canonical_links_20260906,
  $release_20260906_canonical_links_01_01$[{"person_id":"00533bcc-2617-4e9e-9928-ccd6a3799f7c","canonical_person_id":"147c1321-53d1-4dd3-89de-7823697c7098"},{"person_id":"1eef7a03-5e9b-4498-8862-4ca53121993f","canonical_person_id":"2ec71727-7227-4ee6-a5dc-b16493f0ad27"},{"person_id":"8b37e84a-ce1d-4005-a162-f6a49d060237","canonical_person_id":"5b1f1a78-c9e0-44da-a663-eb10ec5f5659"},{"person_id":"b6a1431d-318d-45c8-9653-5f7e3a61b8cc","canonical_person_id":"257ed283-b986-4575-b9a2-eb4e13adb4df"},{"person_id":"c5d78074-a8d5-44c4-8f8c-713cdd344ff6","canonical_person_id":"c1a80678-c645-4bfb-8d93-73423c5f7aaa"},{"person_id":"d230fb3d-2814-4219-9084-7eaed8820a61","canonical_person_id":"320c38ea-48a7-4cfb-a77b-5842abcda5ac"}]$release_20260906_canonical_links_01_01$::jsonb
);
DO $check$
BEGIN
 IF (SELECT count(*) FROM release_staging_20260906._canonical_links_20260906) <> 6
 THEN RAISE EXCEPTION 'Staging count mismatch after canonical_links part 01'; END IF;
END
$check$;
COMMIT;
