-- Generated by scripts/build-2026-registration-polling-production-release.mjs
-- Stages the final reviewed full-local public rows. Loading staging tables does
-- not change any public surface; the final migration applies and verifies them.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '5min';
CREATE SCHEMA IF NOT EXISTS release_staging_20260906;
REVOKE ALL ON SCHEMA release_staging_20260906 FROM PUBLIC, anon, authenticated;
DROP TABLE IF EXISTS
  release_staging_20260906._people_20260906,
  release_staging_20260906._races_20260906,
  release_staging_20260906._merge_decisions_20260906,
  release_staging_20260906._candidates_20260906,
  release_staging_20260906._lifecycle_events_20260906,
  release_staging_20260906._registration_roster_20260906,
  release_staging_20260906._polling_sources_20260906,
  release_staging_20260906._polling_places_20260906,
  release_staging_20260906._polling_neighborhoods_20260906,
  release_staging_20260906._canonical_links_20260906,
  release_staging_20260906._required_races_20260906;
CREATE UNLOGGED TABLE release_staging_20260906._people_20260906
  (LIKE public.people INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._races_20260906
  (LIKE public.races INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._merge_decisions_20260906
  (LIKE public.person_merge_decisions INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._candidates_20260906
  (LIKE public.candidates INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._lifecycle_events_20260906
  (LIKE public.candidate_lifecycle_events INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._registration_roster_20260906
  (LIKE public.registration_name_roster INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._polling_sources_20260906
  (LIKE public.polling_place_sources INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._polling_places_20260906
  (LIKE public.polling_places INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._polling_neighborhoods_20260906
  (LIKE public.polling_place_neighborhoods INCLUDING DEFAULTS);
CREATE UNLOGGED TABLE release_staging_20260906._canonical_links_20260906
  (person_id uuid NOT NULL, canonical_person_id uuid NOT NULL);
CREATE UNLOGGED TABLE release_staging_20260906._required_races_20260906
  (id uuid NOT NULL);
COMMIT;
