-- Generated by scripts/build-production-profile-finance-release.mjs
-- from final reviewed rows in the full local Supabase database.
BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '15min';

CREATE TEMP TABLE _release_people ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_people_20260820;

CREATE TEMP TABLE _release_candidates ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_candidates_20260820;

CREATE TEMP TABLE _release_claims ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_claims_20260820;

CREATE TEMP TABLE _release_affiliations ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_affiliations_20260820;

CREATE TEMP TABLE _release_finance ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_finance_20260820;

CREATE TEMP TABLE _release_people_keys ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_people_keys_20260820;

CREATE TEMP TABLE _release_candidate_keys ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_candidate_keys_20260820;

CREATE TEMP TABLE _release_race_keys ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_race_keys_20260820;

CREATE TEMP TABLE _release_party_keys ON COMMIT DROP AS
SELECT * FROM release_staging_20260820._production_release_party_keys_20260820;

DO $$
BEGIN
    IF (SELECT COUNT(*) FROM _release_people) <> 1727
       OR (SELECT COUNT(*) FROM _release_candidates) <> 34
       OR (SELECT COUNT(*) FROM _release_claims) <> 3672
       OR (SELECT COUNT(*) FROM _release_affiliations) <> 1910
       OR (SELECT COUNT(*) FROM _release_finance) <> 55 THEN
        RAISE EXCEPTION 'Production profile and finance payload count drift';
    END IF;
END
$$;

CREATE TEMP TABLE _release_people_ids ON COMMIT DROP AS
SELECT incoming.local_id, existing.id AS target_id
FROM _release_people_keys incoming
LEFT JOIN public.people existing ON existing.external_id = incoming.external_id;

CREATE TEMP TABLE _release_race_ids ON COMMIT DROP AS
SELECT incoming.local_id, existing.id AS target_id
FROM _release_race_keys incoming
LEFT JOIN public.races existing ON existing.external_id = incoming.external_id;

CREATE TEMP TABLE _release_party_ids ON COMMIT DROP AS
SELECT incoming.local_id, existing.id AS target_id
FROM _release_party_keys incoming
LEFT JOIN public.parties existing ON existing.external_id = incoming.external_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM _release_people_ids WHERE target_id IS NULL)
       OR EXISTS (SELECT 1 FROM _release_race_ids WHERE target_id IS NULL)
       OR EXISTS (SELECT 1 FROM _release_party_ids WHERE target_id IS NULL) THEN
        RAISE EXCEPTION 'Production profile and finance payload is missing a core mapping';
    END IF;
END
$$;

UPDATE _release_candidates incoming
SET person_id = mapping.target_id
FROM _release_people_ids mapping
WHERE incoming.person_id = mapping.local_id;

UPDATE _release_candidates incoming
SET race_id = mapping.target_id
FROM _release_race_ids mapping
WHERE incoming.race_id = mapping.local_id;

UPDATE _release_claims incoming
SET person_id = mapping.target_id
FROM _release_people_ids mapping
WHERE incoming.person_id = mapping.local_id;

UPDATE _release_affiliations incoming
SET person_id = mapping.target_id
FROM _release_people_ids mapping
WHERE incoming.person_id = mapping.local_id;

UPDATE _release_finance incoming
SET party_id = mapping.target_id
FROM _release_party_ids mapping
WHERE incoming.party_id = mapping.local_id;

UPDATE _release_candidates incoming
SET id = existing.id
FROM public.candidates existing
WHERE existing.external_id = incoming.external_id;

UPDATE _release_candidates incoming
SET id = gen_random_uuid()
WHERE EXISTS (
    SELECT 1 FROM public.candidates existing
    WHERE existing.id = incoming.id
      AND existing.external_id IS DISTINCT FROM incoming.external_id
);

UPDATE _release_claims incoming
SET id = existing.id
FROM public.person_claims existing
WHERE existing.claim_key = incoming.claim_key;

UPDATE _release_claims incoming
SET id = gen_random_uuid()
WHERE EXISTS (
    SELECT 1 FROM public.person_claims existing
    WHERE existing.id = incoming.id
      AND existing.claim_key IS DISTINCT FROM incoming.claim_key
);

UPDATE _release_affiliations incoming
SET id = existing.id
FROM public.person_party_affiliations existing
WHERE existing.affiliation_key = incoming.affiliation_key;

UPDATE _release_affiliations incoming
SET id = gen_random_uuid()
WHERE EXISTS (
    SELECT 1 FROM public.person_party_affiliations existing
    WHERE existing.id = incoming.id
      AND existing.affiliation_key IS DISTINCT FROM incoming.affiliation_key
);

UPDATE _release_finance incoming
SET id = existing.id
FROM public.party_annual_finance_filings existing
WHERE existing.party_id = incoming.party_id
  AND existing.report_year = incoming.report_year;

UPDATE _release_finance incoming
SET id = gen_random_uuid()
WHERE EXISTS (
    SELECT 1 FROM public.party_annual_finance_filings existing
    WHERE existing.id = incoming.id
      AND (existing.party_id, existing.report_year)
          IS DISTINCT FROM (incoming.party_id, incoming.report_year)
);

UPDATE public.people target
SET
    gender = incoming.gender,
    education = incoming.education,
    experience = incoming.experience,
    updated_at = NOW()
FROM _release_people incoming
WHERE target.external_id = incoming.external_id;

INSERT INTO public.candidates (id, person_id, race_id, party, candidate_no, registration_status, source_name, source_url, is_public, created_at, updated_at, external_id, vote_count, vote_rate, is_elected, is_incumbent, candidacy_status, election_result, status_updated_at)
SELECT id, person_id, race_id, party, candidate_no, registration_status, source_name, source_url, is_public, created_at, updated_at, external_id, vote_count, vote_rate, is_elected, is_incumbent, candidacy_status, election_result, status_updated_at FROM _release_candidates
ON CONFLICT (external_id) DO UPDATE SET
    person_id = EXCLUDED.person_id,
    race_id = EXCLUDED.race_id,
    party = EXCLUDED.party,
    candidate_no = EXCLUDED.candidate_no,
    registration_status = EXCLUDED.registration_status,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    is_public = EXCLUDED.is_public,
    updated_at = EXCLUDED.updated_at,
    external_id = EXCLUDED.external_id,
    vote_count = EXCLUDED.vote_count,
    vote_rate = EXCLUDED.vote_rate,
    is_elected = EXCLUDED.is_elected,
    is_incumbent = EXCLUDED.is_incumbent,
    candidacy_status = EXCLUDED.candidacy_status,
    election_result = EXCLUDED.election_result,
    status_updated_at = EXCLUDED.status_updated_at;

CREATE TEMP TABLE _release_candidate_ids ON COMMIT DROP AS
SELECT incoming.local_id, existing.id AS target_id
FROM _release_candidate_keys incoming
LEFT JOIN public.candidates existing ON existing.external_id = incoming.external_id;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM _release_candidate_ids WHERE target_id IS NULL) THEN
        RAISE EXCEPTION 'Production release claim candidate mapping is incomplete';
    END IF;
END
$$;

UPDATE _release_claims incoming
SET candidate_id = mapping.target_id
FROM _release_candidate_ids mapping
WHERE incoming.candidate_id = mapping.local_id;

INSERT INTO public.person_claims (id, claim_key, person_id, source_person_id, claim_type, claim_value, claim_json, confidence_level, review_status, visibility, source_name, source_url, observed_at, is_public, created_at, updated_at, review_score, scoring_version, scoring_reasons, auto_reviewed_at, candidate_id)
SELECT id, claim_key, person_id, source_person_id, claim_type, claim_value, claim_json, confidence_level, review_status, visibility, source_name, source_url, observed_at, is_public, created_at, updated_at, review_score, scoring_version, scoring_reasons, auto_reviewed_at, candidate_id FROM _release_claims
ON CONFLICT (claim_key) DO UPDATE SET
    claim_key = EXCLUDED.claim_key,
    person_id = EXCLUDED.person_id,
    source_person_id = EXCLUDED.source_person_id,
    claim_type = EXCLUDED.claim_type,
    claim_value = EXCLUDED.claim_value,
    claim_json = EXCLUDED.claim_json,
    confidence_level = EXCLUDED.confidence_level,
    review_status = EXCLUDED.review_status,
    visibility = EXCLUDED.visibility,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    observed_at = EXCLUDED.observed_at,
    is_public = EXCLUDED.is_public,
    updated_at = EXCLUDED.updated_at,
    review_score = EXCLUDED.review_score,
    scoring_version = EXCLUDED.scoring_version,
    scoring_reasons = EXCLUDED.scoring_reasons,
    auto_reviewed_at = EXCLUDED.auto_reviewed_at,
    candidate_id = EXCLUDED.candidate_id;

INSERT INTO public.person_party_affiliations (id, affiliation_key, person_id, source_person_id, source_claim_key, party_name, normalized_party, role_context, observed_year, observed_date, start_date, end_date, is_current, confidence_level, review_status, source_name, source_url, source_payload, is_public, created_at, updated_at, role_title, organization_unit, display_order, role_tier)
SELECT id, affiliation_key, person_id, source_person_id, source_claim_key, party_name, normalized_party, role_context, observed_year, observed_date, start_date, end_date, is_current, confidence_level, review_status, source_name, source_url, source_payload, is_public, created_at, updated_at, role_title, organization_unit, display_order, role_tier FROM _release_affiliations
ON CONFLICT (affiliation_key) DO UPDATE SET
    affiliation_key = EXCLUDED.affiliation_key,
    person_id = EXCLUDED.person_id,
    source_person_id = EXCLUDED.source_person_id,
    source_claim_key = EXCLUDED.source_claim_key,
    party_name = EXCLUDED.party_name,
    normalized_party = EXCLUDED.normalized_party,
    role_context = EXCLUDED.role_context,
    observed_year = EXCLUDED.observed_year,
    observed_date = EXCLUDED.observed_date,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    is_current = EXCLUDED.is_current,
    confidence_level = EXCLUDED.confidence_level,
    review_status = EXCLUDED.review_status,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    source_payload = EXCLUDED.source_payload,
    is_public = EXCLUDED.is_public,
    updated_at = EXCLUDED.updated_at,
    role_title = EXCLUDED.role_title,
    organization_unit = EXCLUDED.organization_unit,
    display_order = EXCLUDED.display_order,
    role_tier = EXCLUDED.role_tier;

INSERT INTO public.party_annual_finance_filings (id, party_id, report_year, filing_status, ratification_status, assembly_approval_status, detail_url, report_pdf_url, source_name, source_url, is_public, created_at, updated_at)
SELECT id, party_id, report_year, filing_status, ratification_status, assembly_approval_status, detail_url, report_pdf_url, source_name, source_url, is_public, created_at, updated_at FROM _release_finance
ON CONFLICT (party_id, report_year) DO UPDATE SET
    party_id = EXCLUDED.party_id,
    report_year = EXCLUDED.report_year,
    filing_status = EXCLUDED.filing_status,
    ratification_status = EXCLUDED.ratification_status,
    assembly_approval_status = EXCLUDED.assembly_approval_status,
    detail_url = EXCLUDED.detail_url,
    report_pdf_url = EXCLUDED.report_pdf_url,
    source_name = EXCLUDED.source_name,
    source_url = EXCLUDED.source_url,
    is_public = EXCLUDED.is_public,
    updated_at = EXCLUDED.updated_at;

DO $$
DECLARE
    retired_count INTEGER;
BEGIN
    DELETE FROM public.person_claims
    WHERE claim_key = ANY (ARRAY['cec-platform:2022:votetw-candidate-2dc25cd451b5d2ac', 'cec-platform:2022:votetw-candidate-597a55452c5fe998', 'cec-platform:2022:votetw-candidate-0c213f5efb13e949', 'cec-platform:2022:votetw-candidate-de3eb31e853ca5af', 'cec-platform:2022:votetw-candidate-345fbbea6f58b0e4']);
    GET DIAGNOSTICS retired_count = ROW_COUNT;
    IF EXISTS (
        SELECT 1 FROM public.person_claims
        WHERE claim_key = ANY (ARRAY['cec-platform:2022:votetw-candidate-2dc25cd451b5d2ac', 'cec-platform:2022:votetw-candidate-597a55452c5fe998', 'cec-platform:2022:votetw-candidate-0c213f5efb13e949', 'cec-platform:2022:votetw-candidate-de3eb31e853ca5af', 'cec-platform:2022:votetw-candidate-345fbbea6f58b0e4'])
    ) THEN
        RAISE EXCEPTION 'One or more invalid platform claims remain after retirement';
    END IF;
    RAISE NOTICE 'Retired % invalid platform claims', retired_count;
END
$$;

SELECT public.refresh_public_people_list_cached();
SELECT published.promote(NULL);

DO $$
BEGIN
    IF (SELECT COUNT(*) FROM public.person_claims claim
        JOIN _release_claims release ON release.claim_key = claim.claim_key
        WHERE claim.review_status = 'verified'
          AND claim.visibility = 'public'
          AND claim.is_public = TRUE) <> 3672 THEN
        RAISE EXCEPTION 'Production release claims were not fully published';
    END IF;
    IF (SELECT COUNT(*) FROM published.candidates candidate
        JOIN _release_candidates release ON release.id = candidate.candidate_id) <> 34 THEN
        RAISE EXCEPTION 'Production release candidates were not fully published';
    END IF;
    IF (SELECT COUNT(*) FROM published.party_annual_finance_filings) <> 55 THEN
        RAISE EXCEPTION 'Production annual finance filings were not fully published';
    END IF;
END
$$;

DROP TABLE
    release_staging_20260820._production_release_people_20260820,
    release_staging_20260820._production_release_candidates_20260820,
    release_staging_20260820._production_release_claims_20260820,
    release_staging_20260820._production_release_affiliations_20260820,
    release_staging_20260820._production_release_finance_20260820,
    release_staging_20260820._production_release_people_keys_20260820,
    release_staging_20260820._production_release_candidate_keys_20260820,
    release_staging_20260820._production_release_race_keys_20260820,
    release_staging_20260820._production_release_party_keys_20260820;
DROP SCHEMA release_staging_20260820;

COMMIT;
